services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      TZ: America/La_Paz
      POSTGRES_DB: infra
      POSTGRES_USER: infrauser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:7
    container_name: valkey
    restart: always
    command: ["valkey-server"]
    ports:
      - "6379:6379"
    volumes:
      - valkeydata:/data

volumes:
  pgdata:
  valkeydata:
