FROM node:20-alpine AS builder
WORKDIR /app

COPY . .
RUN yarn install --frozen-lockfile
RUN yarn rw build web

# ============= RUNTIME =============
FROM nginx:stable-alpine
COPY --from=builder /app/web/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
