FROM node:20-alpine AS builder
WORKDIR /app

COPY . .
RUN yarn install --frozen-lockfile
RUN yarn rw build api

# ============= RUNTIME =============
FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/api/dist ./api/dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 8911

CMD ["yarn", "rw", "serve", "api"]
